# this is a comment line
# empty lines are also comments
# lines only containing whitespace and semicolons are also discarded as comment!
# all whitespace is optional by default
# key-value pairs are separated by '='
key1 = value;
# keys can have several values separated by commas, NOT whitespace
key2 = value, pair;
# keys can also exist without values
key3;
# keys do not have to be unique, all values will be concatenated automatically
foo = bar;
foo = baz; #equivalent to `foo = bar,baz;`

# all 'server' blocks must have a root, defining it here will propogate it to 
# the inner blocks
root = ./www;
# blocks:tm: are defined as
# [type rws] [identifier rws] { *(comment line | key-value pair | block) } ;
# types, identifiers, keys and values must be fully tchar
{
	http {
		server myServer {
			key = value;
			# servers must have a unique port to listen to, and they must have a
			# port
			listen = 8080;
			# the error block type is special, in that it doesnt inherit values
			# from its parent block
			error {
				400 = ./www/error/400.html;
				404 = ./www/error/404.html;
			};
			cgi = .hs,.py,.sh,.cgi; # list of file extensions that will execute CGIs
			cgidir = ./www/cgi-bin/; # list of directories that will run binaries as if they were CGIs
			allowedmethods = GET,POST,DELETE; # list of HTTP allowed HTTP methods; default value: GET,POST,DELETE
			datadir = ./tmp/data/; # list of directories that may be POST/DELETed to/from
			maxrequestsize = 1024; # maximum size of a request (startline + headers + body)
			# the routes block is like the error block in that it does not
			# inherit values. any key-value pairs are considered mappings from
			# requests to paths on the filesystem
			route {
				/foo = ./www/bar; # any request to /foo maps to ./www/bar on the host filesystem
				/cgi = ./www/cgi-bin;
				/data = ./tmp/data/;
			};
		};
		server yourServer {
			listen = localhost:8081;
			root = ./static-website-example;
			index = index.html; # if the requested file happens to be a directory but doesnt end in '/', instead append /{value} to it
			autoindex; # special key, if it exists, directories will be automatically indexed if requested
			# if autoindex and index are defined at the same time, autoindexing will only happen if the request has a trailing '/'
			error {
				404 = ./static-website-example/error/index.html;
			};
		};
		server {
			listen = 127.0.0.1:8082;
		};
		server essentiallyOff {
			listen = 8083;
			maxrequestsize = 1;
		};
		server {
			listen = 8084;
			route {
				/foo = ./bar;
			};
			datadir = ./www/;
		};
	};
};

# comments and empty lines are delimited by newlines, everything else needs
# semicolons
