# this is a comment line
# empty lines are also comments
# lines only containing whitespace and semicolons are also discarded as comment!
# all whitespace is optional by default
# key-value pairs are separated by '='
key1 = value;
# keys can have several values separated by commas, NOT whitespace
key2 = value, pair;
# keys can also exist without values
key3;
# keys do not have to be unique, all values will be concatenated automatically
foo = bar;
foo = baz; #equivalent to `foo = bar,baz;`

# blocks:tm: are defined as
# [type rws] [identifier rws] { *(comment line | key-value pair | block) } ;
# types, identifiers, keys and values must be fully tchar
{
	http {
		server myServer {
			key = value;
		};
		server yourServer {
		};
	};
};

# comments and empty lines are delimited by newlines, everything else needs
# semicolons
