# this is a comment line
# all whitespace is optional by default
# key-value pairs are separated by '='
key = value;
# keys can have several values separated by commas
key = value, pair;
# keys can also exist without values
key;
# keys do not have to be unique, all values will be concatenated automatically
foo = bar;
foo = baz; #equivalent to `foo = bar,baz;`

# blocks:tm: are defined as
# [type rws] [identifier rws] { *(comment line | key-value pair | block) } ;
# types, identifiers, keys and values cannot have whitespaces in them
# values cannot have commas
{
	http {
		server myServer {
			key = value;
		};
		server yourServer {
		};
	};
};

# comments and empty lines are delimited by newlines, everything else needs
# semicolons
